SQLALCHEMY_DATABASE_URI: 'postgresql://postgres:postgres@127.0.0.1:5432/trondheim'

LOAD_SITUATION: &load_situation
  lat: 10.393333
  lon: 63.429722
  zoom: 12

ZOOM_LIMITS: &zoom_limits
  from: 7
  to: 12

DATA_RETRIEVAL_PWD: "blabla"

QGIS: &qgis
  server_address: "http://trondheim.routr.dk/data"

DEV: &development
  dev: True
