SQLALCHEMY_DATABASE_URI: 'postgresql://sharingcph:sharingcph@127.0.0.1:5432/trondheim'

DEVELOPMENT: true

LOAD_SITUATION: &load_situation
  lat: 10.4026
  lon: 63.419444
  zoom: 13

ZOOM_LIMITS: &zoom_limits
  from: 7
  to: 15

DATA_RETRIEVAL_PWD: "blabla"

QGIS: &qgis
  server_address: "http://www.dr.dk/data"